-- Converte a coluna id de municipio_piloto para IDENTITY (auto-increment).
-- Necessário para que @GeneratedValue(IDENTITY) funcione corretamente no ETL.
ALTER TABLE municipio_piloto ALTER COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
