-- link: ligação entre atendimentos, profissionais e jornadas
CREATE TABLE IF NOT EXISTS link (
    chave           VARCHAR(100)    NOT NULL,
    municipio       VARCHAR(100),
    id_digsaude_ref BIGINT,
    id_jornd_ref    BIGINT,
    id_user_ref     BIGINT,
    ano             INTEGER,
    mes             INTEGER,
    mes_ano         VARCHAR(20),
    CONSTRAINT pk_link PRIMARY KEY (chave)
);

-- munaprov_piloto: municípios aprovados no programa piloto
CREATE TABLE IF NOT EXISTS munaprov_piloto (
    id            BIGINT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    municipio     VARCHAR(100)    NOT NULL,
    cnes_indicado VARCHAR(20),
    CONSTRAINT pk_munaprov_piloto PRIMARY KEY (id)
);

-- maps_off: municípios para mapa offline
CREATE TABLE IF NOT EXISTS maps_off (
    co_ibge    VARCHAR(10)     NOT NULL,
    municipio  VARCHAR(100),
    CONSTRAINT pk_maps_off PRIMARY KEY (co_ibge)
);
